import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  form: {
    background: '#ffffff',
    borderRadius: 12,
    padding: '24px 20px',
    border: '1px solid #e3e2e0',
    color: '#37352f',
    fontFamily: "'Pretendard', sans-serif",
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 16,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: '#6b7280',
  },
  input: {
    height: 40,
    borderRadius: 8,
    border: '1.5px solid #edece9',
    background: '#ffffff',
    color: '#37352f',
    padding: '0 12px',
    fontSize: 14,
    outline: 'none',
    transition: 'border-color 0.15s',
  },
  select: {
    height: 40,
    borderRadius: 8,
    border: '1.5px solid #edece9',
    background: '#ffffff',
    color: '#37352f',
    padding: '0 12px',
    fontSize: 14,
    outline: 'none',
    cursor: 'pointer',
  },
  errorText: {
    color: '#e74c3c',
    fontSize: 12,
    fontWeight: 500,
  },
  actions: {
    display: 'flex',
    gap: 12,
    marginTop: 24,
    justifyContent: 'flex-end',
  },
  submitBtn: {
    background: '#0c73e8',
    color: '#fff',
    border: 'none',
    padding: '10px 24px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 14,
  },
  cancelBtn: {
    background: '#f3f4f6',
    border: '1.5px solid #edece9',
    color: '#4b5563',
    padding: '10px 24px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: 14,
  },
  uploadBox: {
    border: '2px dashed #e3e2e0',
    borderRadius: 8,
    padding: '16px 20px',
    textAlign: 'center',
    background: '#f9fafb',
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },
  uploadLabel: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    display: 'block',
    width: '100%',
  },
  fileList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 10,
    background: '#f9fafb',
    padding: 12,
    borderRadius: 8,
    border: '1px solid #edece9',
  },
  fileItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: '#ffffff',
    padding: '6px 12px',
    borderRadius: 6,
    border: '1px solid #edece9',
  },
  fileName: {
    fontSize: 13,
    color: '#37352f',
    fontWeight: 500,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '85%',
  },
  fileRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: '#ef4444',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 'bold',
    padding: '2px 6px',
  },
};
